config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :games do
    member do
      patch :join
    end
    resources :pieces, only: [:show, :update]
  end
  resources :users, only: :show

  mount ActionCable.server, at: '/cable'
end

app/views/partials/_footer.html.erb
<section class="footer">
  <div class="footer-wrapper">
    <div class="footer-header">
     <p>&copy; 2017 | Camelot Chess</p>
    </div>
  </div>
</section>

app/views/partials/_forfeit_button.html.erb
<div class="buttons">
  <a class="forfeit-btn"<%= link_to 'Forfeit Game', game_path, method: :delete %></a>
</div>

app/views/partials/_navbar.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper <%= @clear_navbar? + 'clear' : '' %>">
    <a href="javascript:void(0)" class="logo">
      <!--<img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_square.png" alt="Logo Image">
    </a>-->
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">MENU</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu">
      <li class="nav-link left"><%= link_to 'Home', root_path %></li>
        <% if user_signed_in? %>
        <li class="nav-link"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
        <li class="nav-link"><%= link_to 'Join Game', games_path %></li>
        <li class="nav-link"><%= link_to 'Create Game', new_game_path %></li>
        <li class="nav-link"><%= link_to 'My Profile', user_path(current_user) %></li>
        <% else %>
        <li class="nav-link"><%= link_to 'Sign Up', new_user_registration_path %></li>
        <li class="nav-link"><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/partials/_navigation.html.erb
<div class="modal">
  <label for="modal-1">
    <div class="modal-trigger">Sign In</div>
  </label>
  <input class="modal-state" id="modal-1" type="checkbox" />
  <div class="modal-fade-screen">
    <div class="modal-inner">
      <div class="modal-close" for="modal-1"></div>
      <p class="modal-content">
      <% if current_user %>
        <li>Hello, <%= current_user.email %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, :method => "delete" %></li>
      <% else %>
        <%= render "devise/sessions/new" %>
      <% end %></p>
    </div>
  </div>
</div>
<div class="log-out">
  <% if current_user %>
    <p><%= link_to "Sign Out", destroy_user_session_path, :method => "delete" %></p>
  <% end %>
</div>

app/views/partials/_promotion_modal.html.erb
<div class="modal">
  <label for="promo-modal">
    <div class="modal-trigger">Click for Modal</div>
  </label>
  <input class="modal-state" id="promo-modal" type="checkbox" />
  <div class="modal-fade-screen">
    <div class="modal-inner">
      <div class="modal-close" for="promo-modal"></div>
        <div class="promo-modal-text">
          <h1>Pawn Promotion!</h1>
          <h1>Make your selection: </h1>
        </div>
        <form action="#" class="pawn-promotion">
          <div class="promo-selection-container">
            <% [Queen, Knight, Bishop, Rook].each do |piece_type| %>
              <div class="promo-selection">
                <label>
                  <%= image_tag(piece_type.new(color: current_color).piece_image) %>
                  <%= piece_type.name %>
                  <input type="radio" name="promo-piece" value="<%= piece_type.name %>">
                </label>
              </div>
            <% end %>  
          </div>
          <br/>
          <div class="promo-selection-submit">
            <input type="submit">
          </div>
        </form>
    </div>
  </div>
</div>