config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#index'
  resources :games do
    member do
      patch :join
    end
    resources :pieces, only: [:show, :update]
  end
  resources :users, only: :show

  mount ActionCable.server, at: '/cable'
end

app/models/game.rb
# Game will hold all Game Logic, gameboard etc.
require 'pry'
class Game < ApplicationRecord
  belongs_to :white_user, class_name: 'User'
  belongs_to :black_user, class_name: 'User', optional: true

  has_many :pieces

  after_create :fill_board, :first_turn!

  scope :available, -> { where(black_user_id: nil) }

  def available?
    black_user.blank?
  end

  def first_turn!
    update(user_turn: 'WHITE')
  end

  def pass_turn!(color)
    player_turn = color == 'WHITE' ? 'BLACK' : 'WHITE'
    update_attributes(user_turn: player_turn)
  end

  def in_check?(color)
    @enemies_causing_check = []
    king = find_king(color)
    
    if king
      opponents = opponents_pieces(color)
      opponents.each do |piece|
        @enemies_causing_check << piece if piece.valid_move?(king.x_position, king.y_position) == true
      end
    end

    return @enemies_causing_check.any?
  end

  def stalemate?(color)
    your_pieces = my_pieces(color)
    available_moves = []
    your_pieces.each do |piece|
      1.upto(8) do |x|
        1.upto(8) do |y|
          if piece.valid_move?(x, y) && !piece.move_causes_check?(x, y)
            available_moves << [x, y]
          end
        end
      end
    end
    return false if available_moves.any?
    true
  end

  def checkmate?(color)
    return false unless in_check?(color)
    return false if capture_opponent_causing_check?(color)
    return false if i_can_move_out_of_check?(color)
    true
  end

  def i_can_move_out_of_check?(color)
    king = find_king(color)
    x_start = king.x_position
    y_start = king.y_position
    state = false
    ((king.x_position - 1)..(king.x_position + 1)).each do |x|
      ((king.y_position - 1)..(king.y_position + 1)).each do |y|
        king.update(x_position: x, y_position: y) if king.valid_move?(x, y)
        state = true unless in_check?(color)
        king.update(x_position: x_start, y_position: y_start)
      end
    end
    state
  end

  def capture_opponent_causing_check?(color)
    friendlies = my_pieces(color)
    the_liberator = []
    friendlies.each do |friend|
      @enemies_causing_check.each do |enemy|
        the_liberator << friend if friend.valid_move?(enemy.x_position, enemy.y_position) == true
      end
    end
    return true if the_liberator.any?
    false
  end

  def fill_board
    # fill white pieces
    (0..7).each do |i|
      Pawn.create(game_id: id, x_position: i, y_position: 1, color: 'WHITE', state: 'unmoved')
    end

    Rook.create(game_id: id, x_position: 0, y_position: 0, color: 'WHITE', state: 'unmoved')
    Rook.create(game_id: id, x_position: 7, y_position: 0, color: 'WHITE', state: 'unmoved')
    Knight.create(game_id: id, x_position: 1, y_position: 0, color: 'WHITE', state: 'unmoved')
    Knight.create(game_id: id, x_position: 6, y_position: 0, color: 'WHITE', state: 'unmoved')
    Bishop.create(game_id: id, x_position: 2, y_position: 0, color: 'WHITE', state: 'unmoved')
    Bishop.create(game_id: id, x_position: 5, y_position: 0, color: 'WHITE', state: 'unmoved')
    Queen.create(game_id: id, x_position: 3, y_position: 0, color: 'WHITE', state: 'unmoved')
    King.create(game_id: id, x_position: 4, y_position: 0, color: 'WHITE', state: 'unmoved')

    # fill black pieces
    (0..7).each do |i|
      Pawn.create(game_id: id, x_position: i, y_position: 6, color: 'BLACK', state: 'unmoved')
    end

    Rook.create(game_id: id, x_position: 0, y_position: 7, color: 'BLACK', state: 'unmoved')
    Rook.create(game_id: id, x_position: 7, y_position: 7, color: 'BLACK', state: 'unmoved')
    Knight.create(game_id: id, x_position: 1, y_position: 7, color: 'BLACK', state: 'unmoved')
    Knight.create(game_id: id, x_position: 6, y_position: 7, color: 'BLACK', state: 'unmoved')
    Bishop.create(game_id: id, x_position: 2, y_position: 7, color: 'BLACK', state: 'unmoved')
    Bishop.create(game_id: id, x_position: 5, y_position: 7, color: 'BLACK', state: 'unmoved')
    Queen.create(game_id: id, x_position: 3, y_position: 7, color: 'BLACK', state: 'unmoved')
    King.create(game_id: id, x_position: 4, y_position: 7, color: 'BLACK', state: 'unmoved')
  end

  def my_pieces(color)
    friendly_pieces = if color == 'BLACK'
                       'BLACK'
                     else
                       'WHITE'
                     end
    pieces.where(color: friendly_pieces).to_a
  end

  def opponents_pieces(color)
    opposing_color = if color == 'BLACK'
                       'WHITE'
                     else
                       'BLACK'
                     end
    pieces.where(color: opposing_color).to_a
  end

  def available?
    black_user.blank?
  end

  def black_pieces
    pieces.where(color: 'BLACK')
  end

  def white_pieces
    pieces.where(color: 'WHITE')
  end

  def space_occupied?(x, y)
    self.pieces.where(x_position: x, y_position: y).present?
  end

  def piece_image
    "#{color.downcase}_#{piece_type.downcase}.png"
  end

  def find_king(color)
    pieces.find_by(piece_type: "King", color: color)
  end

  def self.all_board_coordinates
    result = []
    (0..7).to_a.each do |x|
      (0..7).to_a.each do |y|
        result << [x, y]
      end
    end
    result
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :join, :destroy]

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to root_path
  end

  def show
    @game = Game.find(params[:id])
    @pieces = @game.pieces
    @black_player = @game.black_user_id
    @white_player = @game.white_user_id
    @messages = Message.all
  end

  def new
    @game = Game.new
  end

  def index
    @games = Game.available
  end

  def create
    game = Game.new(game_params)
    game.white_user = current_user
    game.save
    redirect_to game_path(game)
  end

  def join
    @game = Game.find(params[:id])
    if @game.available?
      @game.black_user = current_user
      assign_black_pieces_to_current_user
      @game.save
      redirect_to game_path(@game)
    else
      render :text, :status => :unprocessable_entity
      redirect_to games_path
    end
  end

  private

  def assign_black_pieces_to_current_user
    @game.black_pieces.each do |piece|
      piece.color = 'BLACK'
      piece.save
    end
  end

  def game_params
    params.require(:game).permit(:game_id, :name, :current_user, :black_user_id, :white_user_id, :turn)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/dashboard.html.erb
<div class="booyah-box">
  <div class="row">
    <div class="col-4">
    </div>

    <div class="col-8">
      <h1>Player Profile</h1>
      <% @game.each do |game| %>
        <%= link_to(game_path(game.id)) do %>
          <%= game.id %>
        <% end %>
      <% end %>
    </div>
  </div>
   <div class="clear"></div>
</div>

app/views/games/index.html.erb
<div class="dashboard-container">
  <div class="available-games-section">
    <div class="available-list">
      <h1> Available Games </h1>
    </div>

    <div class="cards">
      <% @games.each do |game| %>
      <div class="card">
        <div class="card-header">
          <h3> Game: <%= game.name %> </h3>
        </div>
        <div class="card-copy">
          <span class="badge-default"><%= game.white_user.nil? ? 'White is open' : 'Black is Open' %><br /></span><br>
          <span class="badge-default"> Date created: <%= game.created_at.to_date %> <br /></span><br>
          <span class="badge-default"> Opponent: <%= game.white_user.email %> <br /></span>
          <%= button_to 'Join game', join_game_path(game), { class: 'btn btn-success card-btn', action: :join, method: :patch } %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div class="forms">
  <h1>Create a Game</h1>
    <%= simple_form_for @game do |f| %>
      <%= f.input  :name %>
      <%= f.button :submit %>
    <% end %>
</div>

app/views/games/show.html.erb
<script>

$( function() {
  $( ".piece" ).draggable({
    snap: ".piece-square",
    grid: [60, 60],
    containment: ".game-board",
  });

    
  $( ".piece-square" ).droppable({
    accept: ".piece",
    drop: function( event, ui ) {
      var x = $(event.target).data('x');
      var y = $(event.target).data('y');
      var urlUpdatePath = $('.ui-draggable-dragging').data('url');
      console.log(x);
      console.log(y);
      console.log(urlUpdatePath);
         
      $.ajax({
        type: 'PUT',
        url: urlUpdatePath,
        data: { piece: { x_position: x, y_position: y }  },
        success: function(response) {
          if(response == 'OK') {
            console.log(response);
          } else {
            alert(response);
          }
          // cause the page to refresh to align the moved piece on the square.
          //Turbolinks.visit(window.location, { action: 'replace' }); 
          //location.reload();
        }
        });
      }
    }); 
  });

</script>

<h2 class="game-title"><%= @game.name %></h2>
<div class="game-board-container">
  <table class="game-board">
    <% 7.downto(0) do |row| %>
      <tr>
        <% 0.upto(7) do |col| %>

          <td class="piece-square ui-droppable" data-x="<%= col %>" data-y="<%= row %>">
            <% @pieces.each do |piece| %>
              <% if piece.x_position == col && piece.y_position == row %>
                <div class="piece" data-url="<%= game_piece_path(piece.game, piece) %>">
                  <%= image_tag(piece.piece_image) %>
                </div>
              <% end %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <div class="chatRoom">
    <h1>Chat room</h1>
      
    <div id="messages">
      <%= render @messages %>
    </div>
      
    <form>
      <input type="text" data-behavior="room_speaker">
    </form>
  </div>
</div>

<br style="clear: both;" />

<%= render 'partials/forfeit_button' %>


